basePath: /ControlSat
definitions:
  swagger.ErrorResponse:
    properties:
      code:
        example: 500
        type: integer
      message:
        example: Error message
        type: string
    type: object
  swagger.GormModelStub:
    properties:
      created_at:
        example: "2023-10-05T15:04:05Z"
        type: string
      deleted_at:
        example: "2023-10-05T15:04:05Z"
        type: string
      id:
        example: 1
        type: integer
      updated_at:
        example: "2023-10-05T15:04:05Z"
        type: string
    type: object
info:
  contact: {}
  version: "1"
paths:
  /ControlSat/Results:
    get:
      description: Obtine ControlSat
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swagger.GormModelStub'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/swagger.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Obtiene ControlSat
      tags:
      - Controlsat
  /Finandina:
    get:
      description: Obtine ControlSat
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swagger.GormModelStub'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/swagger.ErrorResponse'
      security:
      - ApiKeyAuth2: []
      summary: Obtiene ControlSat
      tags:
      - Finandina
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  ApiKeyAuth2:
    in: header
    name: X-API-KEY
    type: apiKey
swagger: "2.0"
